### ISSUE TITLE
Edit/Delete/Reactivate Jobs

### ISSUE THREAD

**Issue by jerekshoe** [kentonh/ennovar-jobboard#28]
When logged in, a user should be able to:
- ~~See expired jobs (if they are the creator of the job listing)~~
  - ~~Also should have an option to renew the job, resetting the createdAt date~~
- Edit any jobs they have created
- Delete any jobs they have created

**Comment by RyFisher** [comment]
Renew expired job listings is now live.  Edit/Delete job still need to be added
