### ISSUE TITLE
apply Alan's design to pages

### ISSUE THREAD

**Issue by kentonh** [kentonh/ennovar-jobboard#65]
waiting on Alan's designs

**Comment by RyFisher** [comment]
![soft_learnproj_homepage_012816](https://cloud.githubusercontent.com/assets/13050225/12755875/d0c86082-c996-11e5-8c01-5dfa0467cb0e.jpg)

**Comment by RyFisher** [comment]
Things missing from design:
- User listings category
- Search category
- Admin "User List" button
- ~~create/view listing page~~

**Comment by RyFisher** [comment]
![soft_learnproj_interiorpage_020216](https://cloud.githubusercontent.com/assets/13050225/12766886/9707df14-c9cb-11e5-8a79-d4843b179dc5.jpg)

**Comment by zrpearson36** [comment]
Color scheme:
Programming - #FF0000
Design - #FF6600
Business - #009900
IT - #0000FF
Marketing - #6600CC
